data_service_client init
Tehtehteh/news-import pull request #1
Opened 2020-10-02 11:01 UTC by Aleks0010V

data_service_client

returns a list of tuples [(rss_url, rss_parser), ...]
in future will call for DataService back-end

2020-10-02 11:42 UTC, Tehtehteh requested changes

2020-10-02 11:42 UTC, Tehtehteh commented on app/data_service_client.py
> +    parsers = {
Я думаю, это стоит вынести в отдельный класс, который будет отвечать только за маппинг между "str" -> "BaseRssParser".

2020-10-02 11:42 UTC, Tehtehteh commented on app/data_service_client.py
> +    url = ''
Лучше убрать из статики это, а чтоб было аргументом, так более явно

2020-10-02 11:42 UTC, Tehtehteh commented on app/data_service_client.py
> +    def __init__(self, debug):
типы, дефолт значение

2020-10-02 11:42 UTC, Tehtehteh commented on app/data_service_client.py
> +    async def get_sources(self) -> List[Tuple[str, any]]:
```suggestion
    async def get_sources(self) -> List[RSSFeed]:
```

2020-10-02 11:42 UTC, Tehtehteh commented on app/data_service_client.py
> +    async def get_sources(self) -> List[Tuple[str, any]]:
Делай конвертацию тут же

2020-10-02 11:42 UTC, Tehtehteh commented on app/data_service_client.py
> +                async with session.get(DataServiceClient.url) as request:
Он будет не только делать GET на `/api/v1/sources/rss`, а может и на что-то другое. Поэтому выдели конкретно `base_url` и добавляй постфиксы в зависимости от метода:
`get_sources -> base_url + /api/v1/sources/rss`
Хотя тут можно даже переименовать в `get_rss_sources`

2020-10-02 11:42 UTC, Tehtehteh commented on main.py
> +    feeds = [RSSFeed(*feed) for feed in feeds]
Конвертацию делай в дата сервис клиенте

2020-10-02 11:43 UTC, Tehtehteh requested changes

2020-10-02 11:43 UTC, Tehtehteh commented on app/data_service_client.py
> +            response = [
Вынеси этот json в какой-то `stub_data_client_sources.json`

2020-10-02 13:19 UTC, Aleks0010V commented
DataService should return result with structure as in new .json file.
An idea is to import parsers dynamically by their class name with getattr and importlib.

2020-10-03 20:25 UTC, Tehtehteh requested changes

2020-10-03 20:25 UTC, Tehtehteh commented on app/data_service_client.py
> +        result = list()
```suggestion
        result = []
```

2020-10-03 20:25 UTC, Tehtehteh commented on app/data_service_client.py
> +    async def get_rss_sources(self, url: str) -> List[RSSFeed]:
`url` аргумент тут не нужен, кмк, метод точно не будет переиспользуемым, а значит, он должен делать одно: получать лист сурсов, а значит явный аргумент не нужен, ибо урла всегда одна будет

2020-10-03 20:25 UTC, Tehtehteh commented on app/data_service_client.py
> +    async def get_rss_sources(self, url: str) -> List[RSSFeed]:
Так что можно сделать так:
```python
class DataServiceClient:

    @property
    def rss_sources_url(self):
        return f'{self.base_url}/api/v1/sources/rss'
```

2020-10-03 20:25 UTC, Tehtehteh commented on app/implemented_sources.py
> +class ImplementedSources:
Нене, пусть это будет фабрикой именно `RSSFeed`, а не фабрикой парсеров. То есть, этот класс должен создавать экземпляр класса `RSSFeed`

2020-10-03 20:25 UTC, Tehtehteh commented on app/implemented_sources.py
> +            rss_parser = getattr(importlib.import_module(f"parsers.rss.{name}"), name)
Я против импорт-магии в питоне, лучше иметь явный маппинг имплементированных сурсов

2020-10-03 20:25 UTC, Tehtehteh commented on app/implemented_sources.py
> +    def get_source(name: str) -> Union[BaseRSSParser, None]:
`Union[T, None] = Optional[T]`

2020-10-03 20:25 UTC, Tehtehteh commented on main.py
> +    data_client = DataServiceClient(base_url='', debug=True)
`base_url` закинь в клиент

2020-10-04 13:30 UTC, Tehtehteh approved these changes
Найс!

2020-10-04 14:14 UTC, merged